sudo: required

services:
  - docker

cache:
  directories:
  - node_modules

before_install:
  - npm install aglio

script:
  - 'docker build -t ${TRAVIS_REPO_SLUG} .'
  - node_modules/.bin/aglio -i ./docs/apiary.apib -o ./docs/apiary_${TRAVIS_BRANCH}.html

after_success:
  - travis/publish.sh

deploy:
  provider: pages
  local-dir: ./docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master